### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by acudroit** [letterpad/letterpad#367]
- allow users to change their text color
- allow users to change color of quote line

**Comment by acudroit** [comment]
Actually, when you say we can control the appearance of the site by CSS what do you mean exactly? Because I'm trying to change the background color and text but nothing is happening

**Comment by acudroit** [comment]
Also the formatting doesn't look that well from mobile view, such as the quote format it's not appearing at all when I read my blog from mobile view or the h2

**Comment by acudroit** [comment]
Nevermind my browser wasn't updated haha.. haha..

**Comment by acudroit** [comment]
But about the CSS feature, what am I allowed to implement exactly and in which format should I implement it? Using the standard CSS method of perhaps
``` body {
}
```
or is it something more less formal like
```
background-color: xyz;
```
without any brackets?

**Comment by abhisaha1** [comment]
The CSS should be written in the normal way. Like this:

```css
body {
   background: #eee;
   font-size: 20px;
}
```

However this feature has been deactivated. The problem is that reader has the choice to change the theme to light or dark. So any color you use to decorate text, might have a problem when the theme is changed.

I had already added a class to handle css for both. eg.

```css
   body {
      color: #000; /* for light theme */
   }
   .dark body {
        color: #fff; /* for dark theme */
   }
```
This needs to server rendered so that there is no flickering. I haven't done this yet but will be ready soon.. in a week.
